name: Calling workflow test

on: 
  workflow_dispatch:
    inputs:
        environment:
          type: environment

  #schedule:
    #- cron : '57 15 * * *'


jobs:
  call-workflow:
    uses: ./.github/workflows/main.yml
    with: 
      environment: dev
    secrets: inherit
    permissions:
      id-token: write
      contents: write
